### PR TITLE
World code

### PR DESCRIPTION
**Pull request by marceljones**
n/a

### CODE REVIEW

**Comment by marceljones** [comment]
Added my Jamaica branch to the master

**Review by mnmccoy95 — CHANGES_REQUESTED** [review]
remove semicolons at end of each list (city, location, leader)

**Review by cArel116 — CHANGES_REQUESTED** [review]
see Mori's comments

**Comment by marceljones** [comment]
semicolons removed

**Review by mnmccoy95 — APPROVED** [review]

**Review by cArel116 — APPROVED** [review]

**Pull request merged**
